import csv

data = [
    {"title": "Deep learning for AI", "category": "Artificial Intelligence"},
    {"title": "Dual-Stage Automated Classification for Chest X-ray Images Using Deep Learning", "category": "Artificial Intelligence"},
    {"title": "Using Data Mining Approach for Discovering Clinical Skills Competency of Nursing Students", "category": "Artificial Intelligence"},
    {"title": "Formulation of Goal Model Generation from User Stories using Natural Language Processing Techniques Framework", "category": "Artificial Intelligence"},
    {"title": "Skin Burn Depth Classification", "category": "Artificial Intelligence"},
    {"title": "Segmentation and Feature Extraction for Cervical Cancer Detection Using Machine Learning", "category": "Artificial Intelligence"},
    {"title": "Neural network and clustering", "category": "Artificial Intelligence"},
    {"title": "Deep learning and machine learning classification", "category": "Artificial Intelligence"},
    {"title": "A Pattern Discovery Model for Text Mining", "category": "Artificial Intelligence"},
    {"title": "AI in Healthcare: Diagnosis and Treatment", "category": "Artificial Intelligence"},
    {"title": "Autonomous Vehicles using AI", "category": "Artificial Intelligence"},
    {"title": "AI for Predictive Maintenance", "category": "Artificial Intelligence"},
    {"title": "AI-based Natural Language Processing", "category": "Artificial Intelligence"},
    {"title": "Mathematical Modelling", "category": "Computational Modelling"},
    {"title": "Identifying New COVID-19 Cluster As Means Of Preventive Measures", "category": "Computational Modelling"},
    {"title": "Decision Analytics for Disease Alerts", "category": "Computational Modelling"},
    {"title": "Modelling the spread of Leptospirosis disease by incorporating the behaviours of rodents and human", "category": "Computational Modelling"},
    {"title": "Climate Change Modelling", "category": "Computational Modelling"},
    {"title": "Economic Forecasting using Computational Models", "category": "Computational Modelling"},
    {"title": "Simulation of Traffic Flow Dynamics", "category": "Computational Modelling"},
    {"title": "Modelling and Simulation of Biological Systems", "category": "Computational Modelling"},
    {"title": "Secondary Security Layer for Anti-Phishing Technique using Image Processing Algorithm", "category": "Cybersecurity Network"},
    {"title": "Enhancing the phishing website detection model through uniform resources locator analysis", "category": "Cybersecurity Network"},
    {"title": "Enhancing Pharming Attack Detection Model", "category": "Cybersecurity Network"},
    {"title": "Enhancing Phishing Attack Detection Model Through Data Mining and Data Analysis for Better Detection Accuracy", "category": "Cybersecurity Network"},
    {"title": "A Dynamic and Automated Signature Detection Framework for Malware Analysis", "category": "Cybersecurity Network"},
    {"title": "Designing of Security Protocols for Mobile Multihop Relay Based WiMAX Networks", "category": "Cybersecurity Network"},
    {"title": "Scalable Rekeying Secrecy Model for D2D Group Communication in 5G Cellular Networks", "category": "Cybersecurity Network"},
    {"title": "Mitigating MAC Layer Attacks In 5G Cellular Networks", "category": "Cybersecurity Network"},
    {"title": "Quantum Cryptographic Scheme for Mobile Multihop D2D Using Deep Learning Approach", "category": "Cybersecurity Network"},
    {"title": "Blockchain-Based Multifactor Authentication for Future 6G Cellular Network", "category": "Cybersecurity Network"},
    {"title": "Blockchain Based Cybersecurity", "category": "Cybersecurity Network"},
    {"title": "Secure and Dynamic Multiple Junction Selection Routing Protocol in VANET", "category": "Cybersecurity Network"},
    {"title": "IoT based Energy Efficient Solar Panel Tracking and Monitoring System", "category": "Cybersecurity Network"},
    {"title": "Securing Internet-of-things (IoT) through Blockchain", "category": "Cybersecurity Network"},
    {"title": "Securing IoT Devices Through Multi-Factor Authentication Using BlockChain", "category": "Cybersecurity Network"},
    {"title": "Securing Deep Learning Model through DNA encoding scheme", "category": "Cybersecurity Network"},
    {"title": "Cybersecurity in Cloud Computing", "category": "Cybersecurity Network"},
    {"title": "Threat Detection using Machine Learning", "category": "Cybersecurity Network"},
    {"title": "Data Encryption Techniques", "category": "Cybersecurity Network"},
    {"title": "Smart home devices with IoT", "category": "IoT Infrastructure"},
    {"title": "A novel User Interface/Experience (UI/UX) for MySejahtera Usage Among Senior Users in Rural Sarawak (Samarahan, Simunjan and Betong) : Self-Monitoring Module", "category": "IoT Infrastructure"},
    {"title": "Data analytics dashboard of IoT-based water quality monitoring for sustainable smart farming", "category": "IoT Infrastructure"},
    {"title": "Designing an IoT-based Framework for JADAM Organic Farming Method", "category": "IoT Infrastructure"},
    {"title": "IoT based Energy Efficient Solar Panel Tracking and Monitoring System", "category": "IoT Infrastructure"},
    {"title": "Securing Internet-of-things (IoT) through Blockchain", "category": "IoT Infrastructure"},
    {"title": "IoT in Smart Cities", "category": "IoT Infrastructure"},
    {"title": "Industrial IoT Applications", "category": "IoT Infrastructure"},
    {"title": "IoT for Environmental Monitoring", "category": "IoT Infrastructure"},
    {"title": "IoT in Healthcare Systems", "category": "IoT Infrastructure"},
    {"title": "Image recognition software", "category": "Visual Image Processing"},
    {"title": "A New Artificial Neural Network Model to Predict Left Ventricle Remodeling for Clinical Decision and Treatment Strategies", "category": "Visual Image Processing"},
    {"title": "Effects of Visual Granularity in Visual Mnemonics on the learning of reactions in organic chemistry", "category": "Visual Image Processing"},
    {"title": "Physiotherapy movement Recognition and Classification by Deep Learning Approach", "category": "Visual Image Processing"},
    {"title": "Clinically Applicable Machine Learning Model for Classification of COVID-19 Abnormalities using Chest Radiographs", "category": "Visual Image Processing"},
    {"title": "A novel User Interface/Experience (UI/UX) for MySejahtera Usage Among Senior Users in Rural Sarawak (Samarahan, Simunjan and Betong) : Self-Monitoring Module", "category": "Visual Image Processing"},
    {"title": "MyAsthma: From Axiomatization to a new Explainable-Artificial Intelligence-Based Risk Management Model with Progressive Web Application for care of Bronchial Asthma", "category": "Visual Image Processing"},
    {"title": "Decision Support Dashboard Architecture and Design for Smart Farming", "category": "Visual Image Processing"},
    {"title": "Rhizomorph Mycelium Recognition using Deep Learning during Mushroom Cultivation Process", "category": "Visual Image Processing"},
    {"title": "Comparative Analysis 3D Faces based on Expression Intensity information of Malaysian Ethnics data", "category": "Visual Image Processing"},
    {"title": "3D facial features tracking for 4D expression intensity estimation", "category": "Visual Image Processing"},
    {"title": "Evaluation of Existing 3D Facial Features Performance For 3D Facial Expression Using UPM-3DFE Database", "category": "Visual Image Processing"},
    {"title": "Design of A Deep Learning Model with Attention Mechanism for Biometric Re-identification of Green Sea Turtles in Long-term Tracking Scenario, Fundamental Research Grant Scheme", "category": "Visual Image Processing"},
    {"title": "Background Subtraction in Egocentric Videos Depicting Activities of Daily Living, Research Acculturation Collaborative Effort", "category": "Visual Image Processing"},
    {"title": "Passive Biometric Identification of Sea Turtles (Chelonia Mydas), Small Grant Scheme", "category": "Visual Image Processing"},
    {"title": "Image processing in autonomous vehicles", "category": "Visual Image Processing"},
    {"title": "Image analysis for medical diagnosis", "category": "Visual Image Processing"},
    {"title": "Face recognition systems", "category": "Visual Image Processing"},
    {"title": "Software Development in Software Engineering course - Looking into Project Planning and Estimation Using Team Software Process (TSPi) and Scrum", "category": "Web Development"},
    {"title": "E-commerce website development", "category": "Web Development"},
    {"title": "Event-B formal development approach towards verification of IoT communication protocol", "category": "Web Development"},
    {"title": "An extended social force model for mobile crowd steering application simulation during fire evacuation", "category": "Web Development"},
    {"title": "Progressive Web Apps", "category": "Web Development"},
    {"title": "Web Performance Optimization", "category": "Web Development"},
    {"title": "The role of service learning on empowering women in digital economy", "category": "Web Development"},
    {"title": "A Design of Transcribing Tool for Kelabit Language", "category": "Web Development"},
    {"title": "Development of an inventory management system for better management of products in a retail store", "category": "Web Development"},
    {"title": "Managing the attendance of remote employees with an attendance management system", "category": "Web Development"},
        {"title": "Deep learning for AI", "category": "Artificial Intelligence"},
    {"title": "Dual-Stage Automated Classification for Chest X-ray Images Using Deep Learning", "category": "Artificial Intelligence"},
    {"title": "Using Data Mining Approach for Discovering Clinical Skills Competency of Nursing Students", "category": "Artificial Intelligence"},
    {"title": "Formulation of Goal Model Generation from User Stories using Natural Language Processing Techniques Framework", "category": "Artificial Intelligence"},
    {"title": "Skin Burn Depth Classification", "category": "Artificial Intelligence"},
    {"title": "Segmentation and Feature Extraction for Cervical Cancer Detection Using Machine Learning", "category": "Artificial Intelligence"},
    {"title": "Neural network and clustering", "category": "Artificial Intelligence"},
    {"title": "Deep learning and machine learning classification", "category": "Artificial Intelligence"},
    {"title": "A Pattern Discovery Model for Text Mining", "category": "Artificial Intelligence"},
    {"title": "AI in Healthcare: Diagnosis and Treatment", "category": "Artificial Intelligence"},
    {"title": "Autonomous Vehicles using AI", "category": "Artificial Intelligence"},
    {"title": "AI for Predictive Maintenance", "category": "Artificial Intelligence"},
    {"title": "AI-based Natural Language Processing", "category": "Artificial Intelligence"},
    {"title": "Mathematical Modelling", "category": "Computational Modelling"},
    {"title": "Identifying New COVID-19 Cluster As Means Of Preventive Measures", "category": "Computational Modelling"},
    {"title": "Decision Analytics for Disease Alerts", "category": "Computational Modelling"},
    {"title": "Modelling the spread of Leptospirosis disease by incorporating the behaviours of rodents and human", "category": "Computational Modelling"},
    {"title": "Climate Change Modelling", "category": "Computational Modelling"},
    {"title": "Economic Forecasting using Computational Models", "category": "Computational Modelling"},
    {"title": "Simulation of Traffic Flow Dynamics", "category": "Computational Modelling"},
    {"title": "Modelling and Simulation of Biological Systems", "category": "Computational Modelling"},
    {"title": "Secondary Security Layer for Anti-Phishing Technique using Image Processing Algorithm", "category": "Cybersecurity Network"},
    {"title": "Enhancing the phishing website detection model through uniform resources locator analysis", "category": "Cybersecurity Network"},
    {"title": "Enhancing Pharming Attack Detection Model", "category": "Cybersecurity Network"},
    {"title": "Enhancing Phishing Attack Detection Model Through Data Mining and Data Analysis for Better Detection Accuracy", "category": "Cybersecurity Network"},
    {"title": "A Dynamic and Automated Signature Detection Framework for Malware Analysis", "category": "Cybersecurity Network"},
    {"title": "Designing of Security Protocols for Mobile Multihop Relay Based WiMAX Networks", "category": "Cybersecurity Network"},
    {"title": "Scalable Rekeying Secrecy Model for D2D Group Communication in 5G Cellular Networks", "category": "Cybersecurity Network"},
    {"title": "Mitigating MAC Layer Attacks In 5G Cellular Networks", "category": "Cybersecurity Network"},
    {"title": "Quantum Cryptographic Scheme for Mobile Multihop D2D Using Deep Learning Approach", "category": "Cybersecurity Network"},
    {"title": "Blockchain-Based Multifactor Authentication for Future 6G Cellular Network", "category": "Cybersecurity Network"},
    {"title": "Blockchain Based Cybersecurity", "category": "Cybersecurity Network"},
    {"title": "Secure and Dynamic Multiple Junction Selection Routing Protocol in VANET", "category": "Cybersecurity Network"},
    {"title": "IoT based Energy Efficient Solar Panel Tracking and Monitoring System", "category": "Cybersecurity Network"},
    {"title": "Securing Internet-of-things (IoT) through Blockchain", "category": "Cybersecurity Network"},
    {"title": "Securing IoT Devices Through Multi-Factor Authentication Using BlockChain", "category": "Cybersecurity Network"},
    {"title": "Securing Deep Learning Model through DNA encoding scheme", "category": "Cybersecurity Network"},
    {"title": "Cybersecurity in Cloud Computing", "category": "Cybersecurity Network"},
    {"title": "Threat Detection using Machine Learning", "category": "Cybersecurity Network"},
    {"title": "Data Encryption Techniques", "category": "Cybersecurity Network"},
    {"title": "Smart home devices with IoT", "category": "IoT Infrastructure"},
    {"title": "A novel User Interface/Experience (UI/UX) for MySejahtera Usage Among Senior Users in Rural Sarawak (Samarahan, Simunjan and Betong) : Self-Monitoring Module", "category": "IoT Infrastructure"},
    {"title": "Data analytics dashboard of IoT-based water quality monitoring for sustainable smart farming", "category": "IoT Infrastructure"},
    {"title": "Designing an IoT-based Framework for JADAM Organic Farming Method", "category": "IoT Infrastructure"},
    {"title": "IoT based Energy Efficient Solar Panel Tracking and Monitoring System", "category": "IoT Infrastructure"},
    {"title": "Securing Internet-of-things (IoT) through Blockchain", "category": "IoT Infrastructure"},
    {"title": "IoT in Smart Cities", "category": "IoT Infrastructure"},
    {"title": "Industrial IoT Applications", "category": "IoT Infrastructure"},
    {"title": "IoT for Environmental Monitoring", "category": "IoT Infrastructure"},
    {"title": "IoT in Healthcare Systems", "category": "IoT Infrastructure"},
    {"title": "Image recognition software", "category": "Visual Image Processing"},
    {"title": "A New Artificial Neural Network Model to Predict Left Ventricle Remodeling for Clinical Decision and Treatment Strategies", "category": "Visual Image Processing"},
    {"title": "Effects of Visual Granularity in Visual Mnemonics on the learning of reactions in organic chemistry", "category": "Visual Image Processing"},
    {"title": "Physiotherapy movement Recognition and Classification by Deep Learning Approach", "category": "Visual Image Processing"},
    {"title": "Clinically Applicable Machine Learning Model for Classification of COVID-19 Abnormalities using Chest Radiographs", "category": "Visual Image Processing"},
    {"title": "A novel User Interface/Experience (UI/UX) for MySejahtera Usage Among Senior Users in Rural Sarawak (Samarahan, Simunjan and Betong) : Self-Monitoring Module", "category": "Visual Image Processing"},
    {"title": "MyAsthma: From Axiomatization to a new Explainable-Artificial Intelligence-Based Risk Management Model with Progressive Web Application for care of Bronchial Asthma", "category": "Visual Image Processing"},
    {"title": "Decision Support Dashboard Architecture and Design for Smart Farming", "category": "Visual Image Processing"},
    {"title": "Rhizomorph Mycelium Recognition using Deep Learning during Mushroom Cultivation Process", "category": "Visual Image Processing"},
    {"title": "Comparative Analysis 3D Faces based on Expression Intensity information of Malaysian Ethnics data", "category": "Visual Image Processing"},
    {"title": "3D facial features tracking for 4D expression intensity estimation", "category": "Visual Image Processing"},
    {"title": "Evaluation of Existing 3D Facial Features Performance For 3D Facial Expression Using UPM-3DFE Database", "category": "Visual Image Processing"},
    {"title": "Design of A Deep Learning Model with Attention Mechanism for Biometric Re-identification of Green Sea Turtles in Long-term Tracking Scenario, Fundamental Research Grant Scheme", "category": "Visual Image Processing"},
    {"title": "Background Subtraction in Egocentric Videos Depicting Activities of Daily Living, Research Acculturation Collaborative Effort", "category": "Visual Image Processing"},
    {"title": "Passive Biometric Identification of Sea Turtles (Chelonia Mydas), Small Grant Scheme", "category": "Visual Image Processing"},
    {"title": "Image processing in autonomous vehicles", "category": "Visual Image Processing"},
    {"title": "Image analysis for medical diagnosis", "category": "Visual Image Processing"},
    {"title": "Face recognition systems", "category": "Visual Image Processing"},
    {"title": "Software Development in Software Engineering course - Looking into Project Planning and Estimation Using Team Software Process (TSPi) and Scrum", "category": "Web Development"},
    {"title": "E-commerce website development", "category": "Web Development"},
    {"title": "Event-B formal development approach towards verification of IoT communication protocol", "category": "Web Development"},
    {"title": "An extended social force model for mobile crowd steering application simulation during fire evacuation", "category": "Web Development"},
    {"title": "Progressive Web Apps", "category": "Web Development"},
    {"title": "Web Performance Optimization", "category": "Web Development"},
    {"title": "The role of service learning on empowering women in digital economy", "category": "Web Development"},
    {"title": "A Design of Transcribing Tool for Kelabit Language", "category": "Web Development"},
    {"title": "Development of an inventory management system for better management of products in a retail store", "category": "Web Development"},
    {"title": "Managing the attendance of remote employees with an attendance management system", "category": "Web Development"},
]

# Define the CSV file path
csv_file_path = 'project_titles.csv'

# Write data to CSV
with open(csv_file_path, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.DictWriter(file, fieldnames=["title", "category"])
    writer.writeheader()  # Write the header row
    writer.writerows(data)  # Write the data rows