import { Inter } from "next/font/google";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FYPBot",
  description: "Generated by create next app and flask app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white ${inter.className}`}>
        <div id="root" className="flex flex-col min-h-screen">
          <div className="main-content flex-grow">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
